### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by alvarotrigo** [shinnn/uglify-save-license#3]
`The regexp for license statement` link in the docs is broken. 
Therefore it is not clear enough how this component works.

Related with https://github.com/terinjokes/gulp-uglify/issues/234

**Comment by SebastianS90** [comment]
Fixed link is: https://github.com/shinnn/uglify-save-license/blob/master/index.js#L7

**Comment by shinnn** [comment]
Thanks for the report, @alvarotrigo.

@SebastianS90 Your link will be soon broken when I add an additional line above L7. https://github.com/shinnn/uglify-save-license/blob/451c8b0f549dbb74d62096f00b939f9c35942632/index.js#L7 is more stable.

# 

PR welcome 👐

**Comment by alvarotrigo** [comment]
Thanks for the quick reply!
