### ISSUE TITLE
Module vars defined outside exported function are undefined while running UglifyJsPlugin in parallel mode

### ISSUE THREAD

**Issue by melwynfurtado** [shinnn/uglify-save-license#6]
Can I open a PR to move the vars such as `licenseRegexp`, `prevCommentLine` and `prevFile` within the exported function `saveLicense`?

Running `UglifyJsPlugin` with parallelisation on in `Webpack 4` results in an below error...

```
ERROR in bundle.js from UglifyJs
undefined
``` 

On further debugging, it turns out to be `ReferenceError`.

```
ReferenceError: licenseRegexp is not defined
ReferenceError: prevCommentLine is not defined
ReferenceError: prevFile is not defined
```

I am not quite sure what happens when `UglifyJsPlugin` runs in parallel mode to lose access to outer scoped vars.

**Comment by shinnn** [comment]
No. You should fix UglifyJsPlugin instead.
